import { useState, useEffect } from 'react';

// Define the structured TypeScript interface matching the Rust evaluator output
export interface QuantumCellResult {
  status: 'SUCCESS' | 'ERROR';
  algorithm?: string;
  result_summary?: string;
  fidelity?: number;
  iterations_required?: number;
  target_found_at?: string;
  probability_amplitude?: number;
  bits_evaluated?: number;
  security_risk_level?: string;
  target_mode?: string;
  optimal_energy_state?: number;
  convergence_iterations?: number;
  approximation_ratio?: number;
  optimized_cost_index?: number;
  classification_accuracy?: number;
  anomaly_detected?: boolean;
  error_message?: string;
}

/**
 * Custom React hook to initialize and interact with the q-excel WebAssembly engine.
 * Ensures the Rust core compiled binary is safely loaded into the browser context.
 */
export function useQuantumWasm() {
  const [engine, setEngine] = useState<any>(null);
  const [isLoaded, setIsLoaded] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadWasmEngine() {
      try {
        // Dynamically import the WebAssembly bindings generated by wasm-pack
        const wasm = await import('../../../qexcel-bindings/typescript/pkg/q_excel_core');
        
        // Instantiate the high-performance structural engine constructor from Rust
        const engineInstance = new wasm.QuantumEngineWasm();
        
        setEngine(engineInstance);
        setIsLoaded(true);
      } catch (err: any) {
        console.error('Failed to instantiate q-excel core WASM engine:', err);
        setError(err.message || 'WASM compilation error');
      }
    }

    loadWasmEngine();
  }, []);

  /**
   * Routes a raw string formula typed into the spreadsheet UI down to the Rust computation layer.
   * Returns a fully typed QuantumCellResult object.
   */
  const executeQuantumFormula = (formulaStr: string, isSuperposition: boolean): QuantumCellResult => {
    if (!isLoaded || !engine) {
      return { status: 'ERROR', error_message: 'Quantum engine not fully loaded into browser runtime.' };
    }

    try {
      // Execute within high-speed Rust memory blocks and capture the fast JSON string injection
      const rawJsonResult = engine.evaluate_q_cell(isSuperposition);
      return JSON.parse(rawJsonResult) as QuantumCellResult;
    } catch (err: any) {
      return { status: 'ERROR', error_message: err.message || 'Quantum computation breakdown' };
    }
  };

  return { isLoaded, error, executeQuantumFormula };
}
